//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendenceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendence_record
    {
        public int at_id { get; set; }
        public int emp_id { get; set; }
        public System.DateTime attnd_date { get; set; }
    }
}
