//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendenceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_record
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string address { get; set; }
        public System.DateTime created_date { get; set; }
        public int card_status { get; set; }
    }
}
